### ISSUE TITLE
Showing Error when using '\' symbol to add space.

### ISSUE THREAD

**Issue by d2207-sahu** [simpleclub/CaTeX#77] opened 2020-12-18 10:07 UTC
## Bug description

*A clear and concise description of what the bug is.*
I wanted to show space between the latex code but its not possible as the "\" symbol shows error. While other libraries won't.
Here is my Latex Code. 
**Latex Code:**\begin{aligned}&\text { The greatest integer } k \text { for which } 49^{k}+1 \text { is a factor of the sum }\\&49^{125}+49^{124}+\cdots+49^{2}+49+1 \text { is }\end{aligned}
### To Reproduce

0. Use 'Catex()'
0. Run on 'flutter'
0. See an error
 CaTeXException during configuration: Unknown symbol in CaTeXMode.math, for input: \begin

## Expected behavior
Want it to read \ symbole to add the space between the latex code. Other latex code readers doesn't through error but CaTeX throws. Can you please look into the matter. I really love is this Library.

*A clear and concise description of what you expected to happen.*
I want the CaTeX should handle the '\' to show space.

**Screenshots Description**
1. Other sites that render Latex can read the Latex Code.
2. The Error.
3. My Latex Code.

### Screenshots
![image](https://user-images.githubusercontent.com/55633712/102600592-08231d80-4145-11eb-93ae-ac96b9f5c435.png)
![Annotation 2020-12-18 143910](https://user-images.githubusercontent.com/55633712/102600645-196c2a00-4145-11eb-9179-256e14e29f06.jpg)
![Annotation 2020-12-18 143930](https://user-images.githubusercontent.com/55633712/102600655-1b35ed80-4145-11eb-8173-d50c16ab3cee.jpg)

*If applicable, add screenshots to help explain your problem.*

**Comment by creativecreatorormaybenot** [comment] 2020-12-18 10:11
Duplicate of #70.

**Closed by creativecreatorormaybenot** 2020-12-18 10:11 UTC
Labels: bug
